name: Reusable Reek

on:
  workflow_call:
    inputs:
      exclude-files:
        type: string
        required: false
        default: ''
      report-only:
        type: boolean
        required: false
        default: False
      show-errors:
        type: boolean
        required: false
        default: True
      show-skipped:
        type: boolean
        required: false
        default: False

jobs:
  get-ruby-versions:
    name: Get Ruby Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
    - uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f # v0.1.3
      id: get-language-versions
      with:
        language: "ruby"

  reek:
    name: Reek
    needs: get-ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-versions: ${{ fromJson(needs.get-ruby-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up Ruby ${{ matrix.ruby-versions }}
        uses: ruby/setup-ruby@7dc18ff0ca6e3630d3f29d2a85ebf6cc27ae9d6c # v1.147.0
        with:
          ruby-version: ${{ matrix.ruby-versions }}
      - name: Run Reek
        env:
          EXCLUDE_FILES: ${{ inputs.exclude-files }}
          REPORT_ONLY: ${{ inputs.report-only }}
          SHOW_ERRORS: ${{ inputs.show-errors }}
          SHOW_SKIPPED: ${{ inputs.show-skipped }}
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/reek/master/pipeline.sh)
