name: Resuable Purge deprecated workflow runs

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  purge-obsolete-workflows:
    name: Purge deprecated workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Purge obsolete workflow runs
        uses: otto-de/purge-deprecated-workflow-runs@71f15da78bd1a0c0bf5f1a31f1350094a3917df7 # v 1.3.0
        with:
          token: ${{ secrets.token }}
