name: Reusable Pytest

on:
  workflow_call:

jobs:
  get-python-versions:
    name: Get Python Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
    - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
      id: get-language-versions
      with:
        language: "python"

  pytest:
    name: Pytest
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ${{ fromJson(needs.get-python-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install required packages
        run: |
          if [[ -f requirements.txt ]]; then
              pip install -r requirements.txt
          fi
      - name: Install Pytest
        run: |
          pip install pytest
          exit $(( $? == 5 ? 0 : $? ))
      - name: Run Pytest
        run: |
         pytest --no-header -vv
  