name: Reusable Markdown Linting

on:
  workflow_call:

jobs:
  get-node-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
    - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
      id: get-language-versions
      with:
        language: "node"
        highest-only: true
        remove-patch-version: true

  markdown-lint:
    name: Markdown Lint
    needs: get-node-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup node ${{ needs.get-node-version.outputs.version }}
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: ${{ needs.get-node-version.outputs.version }}
      - name: Run Markdown Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/markdown-lint/master/pipeline.sh)
        env:
          EXCLUDE_FILES: "README.md"
