name: Reusable ShellCheck

on:
  workflow_call:
    inputs:
      exclude-files:
        type: string
        default: ''
      report-only:
        type: boolean
        default: False
      show-errors:
        type: boolean
        default: True
      show-skipped:
        type: boolean
        default: False


jobs:
  shellcheck:
    name: ShellCheck (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
        env:
            EXCLUDE_FILES: ${{ inputs.exclude-files }}
            REPORT_ONLY: ${{ inputs.report-only }}
            SHOW_ERRORS: ${{ inputs.show-errors }}
            SHOW_SKIPPED: ${{ inputs.show-skipped }}
  