name: Reusable Markdown Linting

on:
  workflow_call:

jobs:
  get-node-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
    - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
      id: get-language-versions
      with:
        language: "node"
        highest-only: true
        remove-patch-version: true

  markdown-lint:
    name: Markdown Lint
    needs: get-node-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup node ${{ needs.get-node-version.outputs.version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ needs.get-node-version.outputs.version }}
      - name: Run Markdown Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/markdown-lint/master/pipeline.sh)
        env:
          EXCLUDE_FILES: "README.md"
