name: Reusable Bundler

on:
  workflow_call:

jobs:
  get-ruby-versions:
    name: Get Ruby Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
      - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
        id: get-language-versions
        with:
          language: "ruby"
    
  bundler:
    name: Bundler
    needs: get-ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-versions: ${{ fromJson(needs.get-ruby-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Ruby ${{ matrix.ruby-versions }}
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
        with:
          ruby-version: ${{ matrix.ruby-versions }}
      - name: Run Bundle Install
        run: bundle install
      - name: Run Bundle Exec rake
        run: bundle exec rake
