name: Reusable Delete old workflow runs

on:
  workflow_call:
    inputs:
      days:
        type: string
        required: true
      minimum-runs:
        type: string
        required: false
    secrets:
      token:
        required: true

jobs:
  delete-old-workflows:
    name: Delete old workflow runs (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@9835e4abbefe04992885a989df6e3f61ddd60117 # v2.0.4
        with:
          token: ${{ secrets.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: ${{ inputs.minimum-runs }}
