name: Reusable Powershell Linter

on:
  workflow_call:

jobs:
  shellcheck:
    name: ShellCheck (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: lint
        uses: SleepySysadmin/github-action-pscheck@2522a32675c0c3447a479b401ef5f14d33f8f7a2 # v0.4.2

