name: Slack (Reusable)

on:
  workflow_call:
    inputs:
      slack_notify:
        required: true
        type: string
    secrets:
      token:
        required: true
      slack_webhook_url:
        required: true

jobs:
  slack-workflow-status:
    name: Slack (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ inputs.slack_notify == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@26a36836c887f260477432e4314ec3490a84f309 # v1.2.0
        with:
          repo_token: ${{ secrets.token }}
          slack_webhook_url: ${{ secrets.slack_webhook_url }}
          include_jobs: on-failure
          include_commit_message: true
