name: Reusable Greetings

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  greeting:
    name: Handle Greetings (Reusable)
    runs-on: ubuntu-latest
    steps:
    - name: Handle greetings
      uses: actions/first-interaction@1d8459ca65b335265f1285568221e229d45a995e # v1.1.1
      with:
        repo-token: ${{ secrets.token }}
        issue-message: "Thank you for raising your first issue - all contributions to this project are welcome!"
        pr-message: "Thank you for raising your first pull request - all contributions to this project are welcome!"
