name: Reusable Bundler

on:
  workflow_call:

jobs:
  get-ruby-versions:
    name: Get Ruby Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
      - uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f # v0.1.3
        id: get-language-versions
        with:
          language: "ruby"
    
  bundler:
    name: Bundler
    needs: get-ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-versions: ${{ fromJson(needs.get-ruby-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Set up Ruby ${{ matrix.ruby-versions }}
        uses: ruby/setup-ruby@7bae1d00b5db9166f4f0fc47985a3a5702cb58f0 # v1.197.0
        with:
          ruby-version: ${{ matrix.ruby-versions }}
      - name: Run Bundle Install
        run: bundle install
      - name: Run Bundle Exec rake
        run: bundle exec rake
