name: Reusable Pydocstyle

on:
  workflow_call:
    inputs:
      exclude-files:
        type: string
        required: false
        default: ''
      report-only:
        type: boolean
        required: false
        default: False
      show-errors:
        type: boolean
        required: false
        default: True
      show-skipped:
        type: boolean
        required: false
        default: False

jobs:
  get-python-versions:
    name: Get Python Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
    - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
      id: get-language-versions
      with:
        language: "python"

  pydocstyle:
    name: Pydocstyle
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ${{ fromJson(needs.get-python-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Run Pydocstyle
        env:
            EXCLUDE_FILES: ${{ inputs.exclude-files }}
            REPORT_ONLY: ${{ inputs.report-only }}
            SHOW_ERRORS: ${{ inputs.show-errors }}
            SHOW_SKIPPED: ${{ inputs.show-skipped }}
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/pydocstyle/master/pipeline.sh)
