name: Reusable Bundler

on:
  workflow_call:

jobs:
  get-ruby-versions:
    name: Get Ruby Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
      - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
        id: get-language-versions
        with:
          language: "ruby"
    
  bundler:
    name: Bundler
    needs: get-ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-versions: ${{ fromJson(needs.get-ruby-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Set up Ruby ${{ matrix.ruby-versions }}
        uses: ruby/setup-ruby@6bd3d993c602f6b675728ebaecb2b569ff86e99b # v1.174.0
        with:
          ruby-version: ${{ matrix.ruby-versions }}
      - name: Run Bundle Install
        run: bundle install
      - name: Run Bundle Exec rake
        run: bundle exec rake
