name: Resuable Purge deprecated workflow runs

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  purge-obsolete-workflows:
    name: Purge deprecated workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Purge obsolete workflow runs
        uses: otto-de/purge-deprecated-workflow-runs@0de33de0a9fe17321e4cf3c21dcbc0445e7c5b61 # v 1.1.1
        with:
          token: ${{ secrets.token }}
