name: Reusable GitGuardian Scan

on:
  workflow_call:
    secrets:
      token:
        required: true
      gitguardian-api-key:
        required: true

jobs:
  gitguardian-scan:
    name: GitGuardian Scan (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@606e42384cb5dc0b66f3d2fb6a9be6c5328b4a7e # v1.32.1
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA:  ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.gitguardian-api-key }}
