name: Reusable Powershell Linter

on:
  workflow_call:

jobs:
  shellcheck:
    name: ShellCheck (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: lint
        uses: SleepySysadmin/github-action-pscheck@2522a32675c0c3447a479b401ef5f14d33f8f7a2 # v0.4.2

