name: Delete old workflow runs (Reusable)

on:
  workflow_call:
    inputs:
      days:
        type: number
        required: true
      minimum-runs:
        required: true
        type: number
    secrets:
      token:
        required: true

jobs:
  delete-old-workflows:
    name: Delete old workflow runs (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@c1a2f0de3fa4134a2357de83c92acff6e298bb8a # v2.0.3
        with:
          token: ${{ secrets.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: ${{ inputs.minimum-runs }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
