name: Reusable Bundler

on:
  workflow_call:

jobs:
  get-ruby-versions:
    name: Get Ruby Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
      - uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f # v0.1.3
        id: get-language-versions
        with:
          language: "ruby"
    
  bundler:
    name: Bundler
    needs: get-ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-versions: ${{ fromJson(needs.get-ruby-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Ruby ${{ matrix.ruby-versions }}
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999 # v1.191.0
        with:
          ruby-version: ${{ matrix.ruby-versions }}
      - name: Run Bundle Install
        run: bundle install
      - name: Run Bundle Exec rake
        run: bundle exec rake
