name: Reusable Slack

on:
  workflow_call:
    inputs:
      slack_notify:
        required: true
        type: string
    secrets:
      token:
        required: true
      slack_webhook_url:
        required: true

jobs:
  slack-workflow-status:
    name: Slack (Reusable)
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Slack Workflow Notifications
        if: ${{ inputs.slack_notify == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@68bf00d0dbdbcb206c278399aa1ef6c14f74347a # v1.3.0
        with:
          repo_token: ${{ secrets.token }}
          slack_webhook_url: ${{ secrets.slack_webhook_url }}
          include_jobs: on-failure
          include_commit_message: true
