name: Reusable Perl Lint

on:
  workflow_call:
    inputs:
      exclude-files:
        type: string
        default: ''
      report-only:
        type: boolean
        default: False
      show-errors:
        type: boolean
        default: True
      show-skipped:
        type: boolean
        default: False

jobs:
  get-perl-versions:
    name: Get Perl Versions
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}
    steps:
    - uses: ActionsToolbox/get-language-versions-action@9a98a01e87286f073bbee069547aeeea4ea30265 # v0.1.2
      id: get-language-versions
      with:
        language: "perl"

  perl-lint:
    name: Perl Lint
    needs: get-perl-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-versions: ${{ fromJson(needs.get-perl-versions.outputs.version-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Perl ${{ matrix.perl-versions }}
        uses: shogo82148/actions-setup-perl@a898263d06c9cf32dd8b6d3ea28790baf8d30cd5 # v1.24.2
        with:
          perl-version: ${{ matrix.perl-versions }}
      - name: Run Perl Lint
        env:
          EXCLUDE_FILES: ${{ inputs.exclude-files }}
          REPORT_ONLY: ${{ inputs.report-only }}
          SHOW_ERRORS: ${{ inputs.show-errors }}
          SHOW_SKIPPED: ${{ inputs.show-skipped }}
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/perl-lint/master/pipeline.sh)
