name: Reusable Powershell Linter

on:
  workflow_call:

jobs:
  shellcheck:
    name: ShellCheck (Reusable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: lint
        uses: SleepySysadmin/github-action-pscheck@2522a32675c0c3447a479b401ef5f14d33f8f7a2 # v0.4.2

